### PR TITLE
Generate input types [Finishes #157980083]

### PR DESCRIPTION
**Pull request by Bellk17**
Generates input types as well as scans operations to find enumerated types.

### CODE REVIEW

**Review by Kolossion — APPROVED** [review]
:shipit: 🎲

I think refactoring this lib into something a bit easier to work in could be a good thing to put in the "fix tech debt" bucket.

**Comment by Bellk17** [comment]
I started rewriting this awhile back in my free time, but no cigar. Wish I could PR my changes into the original project, but the guy does some dumb stuff.

**Review by jxbadam — APPROVED** [review]
:shipit: :fire:

**Review by scull7 — APPROVED** [review]
:shipit: 🇮🇹

**Pull request merged**
